name: Cache Demo

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create cache directory
        run: mkdir -p ~/.cache-demo && echo "demo-data" > ~/.cache-demo/file.txt

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache-demo
          key: cache-0f52b74
          restore-keys: |
            cache-

      - name: prime-cache-0f52b74
        run: echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"

